import type { ExcelGridData } from "./app/index.ts";

/**
 * 그리드 동작 확인을 위한 테스트용 데이터.
 *
 * 서버 응답 형태를 그대로 사용한다.
 * - 최상위는 `Record<sheetName, SheetBody>` 모양이며, 키가 곧 시트 이름이다.
 * - 각 시트는 `headers`, `data`, `errors` 를 갖는다.
 */
export const SAMPLE_DATA: ExcelGridData = {
    "미들웨어": {
        headers: [
            { key: "id", name: "id", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "assetName", name: "자산명", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "assetCode", name: "자산코드", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "task", name: "업무그룹", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "location", name: "자산위치", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "slaGroup", name: "SLA 그룹", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "department", name: "부서", type: "code", typeName: "Department", subClass: null, subValue: null, targetClass: null },
            { key: "project", name: "프로젝트코드", type: "code", typeName: "ProjectCode", subClass: null, subValue: null, targetClass: null },
            { key: "mngPrimary", name: "1차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "mngSecondary", name: "2차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "mngTertiary", name: "3차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "createdBy", name: "등록자", type: "code", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "updatedBy", name: "수정자", type: "code", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "createdAt", name: "등록일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "updatedAt", name: "수정일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "endOfService", name: "서비스 종료일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "importDate", name: "도입일자", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "importPrice", name: "도입금액", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "mngPrice", name: "유지보수액", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "mngRate", name: "유지보수율", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "etc", name: "부가정보", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "operator", name: "운영 담당자", type: "array", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "handler", name: "자산 사용자", type: "array", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "assetCustomCodesψ22", name: "IP(하드웨어)(C_146)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ23", name: "IP(NAS)(C_101)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ24", name: "자산유형(C_1)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ25", name: "자산유형비고(C_5)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ26", name: "공통코드(테스트용)(C_34)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ27", name: "기타작업(C_10)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ28", name: "기타(C_9)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ29", name: "IP(HB)(C_102)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ30", name: "IP(백업)(C_91)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ31", name: "IP(서비스)(C_90)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomStringsψ32", name: "상태정보(S_1)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ33", name: "테스트정보(S_2)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ34", name: "정보(S_6)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ35", name: "설치일자(S_15)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ36", name: "폐기일자(S_17)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ37", name: "서비스개시일자(S_16)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ38", name: "도입일자(S_7)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ39", name: "담당업체(S_27)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ40", name: "담당자(S_28)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
        ],
        data: [
            { id: "177", assetName: "윈도우 정품 라이선스 21", assetCode: null, task: null, location: "ap-northeast-2a (AZ)", slaGroup: "1등급", department: "신사업개발팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.355497", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "172", assetName: "윈도우 정품 라이선스 16", assetCode: null, task: null, location: "판교 오피스", slaGroup: "1등급", department: "마케팅부", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2026-02-04T16:06:58.299971", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "167", assetName: "윈도우 정품 라이선스 11", assetCode: null, task: null, location: "2층 개발실", slaGroup: "1등급", department: "고객지원팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.356483", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "162", assetName: "윈도우 정품 라이선스 6", assetCode: null, task: null, location: "서버 랙 R-01", slaGroup: "1등급", department: "본사", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.356483", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "157", assetName: "윈도우 정품 라이선스 1", assetCode: null, task: null, location: "Production VPC", slaGroup: "1등급", department: "경영지원부", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.356483", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "152", assetName: "한컴 라이선스 5", assetCode: null, task: null, location: "1층", slaGroup: "1등급", department: "사업기획팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.356483", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
        ],
        errors: null,
    },
    "서버(물리)": {
        headers: [
            { key: "id", name: "id", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "assetName", name: "자산명", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "assetCode", name: "자산코드", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "task", name: "업무그룹", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "location", name: "자산위치", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "slaGroup", name: "SLA 그룹", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "department", name: "부서", type: "code", typeName: "Department", subClass: null, subValue: null, targetClass: null },
            { key: "project", name: "프로젝트코드", type: "code", typeName: "ProjectCode", subClass: null, subValue: null, targetClass: null },
            { key: "mngPrimary", name: "1차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "mngSecondary", name: "2차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "mngTertiary", name: "3차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "createdBy", name: "등록자", type: "code", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "updatedBy", name: "수정자", type: "code", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "createdAt", name: "등록일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "updatedAt", name: "수정일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "endOfService", name: "서비스 종료일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "importDate", name: "도입일자", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "importPrice", name: "도입금액", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "mngPrice", name: "유지보수액", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "mngRate", name: "유지보수율", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "etc", name: "부가정보", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "operator", name: "운영 담당자", type: "array", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "handler", name: "자산 사용자", type: "array", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "assetCustomCodesψ22", name: "IP(하드웨어)(C_146)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ23", name: "IP(NAS)(C_101)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ24", name: "자산유형(C_1)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ25", name: "자산유형비고(C_5)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ26", name: "공통코드(테스트용)(C_34)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ27", name: "기타작업(C_10)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ28", name: "기타(C_9)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ29", name: "IP(HB)(C_102)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ30", name: "IP(백업)(C_91)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ31", name: "IP(서비스)(C_90)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomStringsψ32", name: "상태정보(S_1)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ33", name: "테스트정보(S_2)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ34", name: "정보(S_6)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ35", name: "설치일자(S_15)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ36", name: "폐기일자(S_17)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ37", name: "서비스개시일자(S_16)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ38", name: "도입일자(S_7)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ39", name: "담당업체(S_27)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ40", name: "담당자(S_28)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetFieldsψ41", name: "납품 처리자(F_14)", type: "code", typeName: "UserAccount", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ42", name: "납품일자(F_4)", type: "date", typeName: "AssetField", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ43", name: "납품 검수자(F_13)", type: "code", typeName: "UserAccount", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ44", name: "납품 담당자(F_5)", type: "code", typeName: "UserAccount", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ45", name: "상태 코드(F_1)", type: "code", typeName: "GroupSelect", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ46", name: "짧은 비고(F_2)", type: null, typeName: "AssetField", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ47", name: "긴 비고(F_3)", type: null, typeName: "AssetField", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ48", name: "가상화 여부(F_7)", type: "code", typeName: "GroupSelect", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ49", name: "내용 입력(F_12)", type: null, typeName: "AssetField", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ50", name: "OS(F_9)", type: null, typeName: "AssetField", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ51", name: "입력(F_8)", type: null, typeName: "AssetField", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ52", name: "ㅁㅁㅁ(F_10)", type: null, typeName: "AssetField", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ53", name: "test(F_91)", type: "code", typeName: "GroupSelect", subClass: "field", subValue: "value", targetClass: "AssetField" },
        ],
        data: [
            { id: "13", assetName: "물리서버 #2", assetCode: "AST_00002", task: "서버관리", location: "개발팀 구역", slaGroup: "1등급", department: null, project: "통합ITO", mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: "관리자", updatedBy: "이동희", createdAt: "2026-01-01T00:00", updatedAt: "2025-11-03T10:52:03.916640", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "", "assetCustomCodesψ22": "", "assetCustomCodesψ23": "", "assetCustomCodesψ24": "서버", "assetCustomCodesψ25": "", "assetCustomCodesψ26": "", "assetCustomCodesψ27": "", "assetCustomCodesψ28": "", "assetCustomCodesψ29": "", "assetCustomCodesψ30": "", "assetCustomCodesψ31": "" },
            { id: "11", assetName: "물리서버#1", assetCode: "AST_00001", task: "인프라", location: "회의실 201", slaGroup: "1등급", department: null, project: "통합ITO", mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: "관리자", updatedBy: "이동희", createdAt: "2026-01-01T00:00", updatedAt: "2025-11-03T10:49:25.070188", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "", "assetCustomCodesψ22": "", "assetCustomCodesψ23": "", "assetCustomCodesψ24": "서버", "assetCustomCodesψ25": "", "assetCustomCodesψ26": "", "assetCustomCodesψ27": "", "assetCustomCodesψ28": "", "assetCustomCodesψ29": "", "assetCustomCodesψ30": "", "assetCustomCodesψ31": "" },
            { id: "2", assetName: "하이퍼바이저#1", assetCode: "", task: "서버관리", location: "테스트 서버실", slaGroup: "1등급", department: null, project: "통합ITO", mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: "관리자", updatedBy: "김진태", createdAt: "2026-01-01T00:00", updatedAt: "2025-10-22T20:29:21.990837", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "", "assetCustomCodesψ22": "", "assetCustomCodesψ23": "", "assetCustomCodesψ24": "서버", "assetCustomCodesψ25": "", "assetCustomCodesψ26": "", "assetCustomCodesψ27": "", "assetCustomCodesψ28": "", "assetCustomCodesψ29": "", "assetCustomCodesψ30": "", "assetCustomCodesψ31": "" },
        ],
        errors: null,
    },
    "네트워크 장비": {
        headers: [
            { key: "id", name: "id", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "assetName", name: "자산명", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "assetCode", name: "자산코드", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "task", name: "업무그룹", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "location", name: "자산위치", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "slaGroup", name: "SLA 그룹", type: "code", typeName: "Code", subClass: null, subValue: null, targetClass: null },
            { key: "department", name: "부서", type: "code", typeName: "Department", subClass: null, subValue: null, targetClass: null },
            { key: "project", name: "프로젝트코드", type: "code", typeName: "ProjectCode", subClass: null, subValue: null, targetClass: null },
            { key: "mngPrimary", name: "1차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "mngSecondary", name: "2차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "mngTertiary", name: "3차 유지보수업체", type: "code", typeName: "Company", subClass: null, subValue: null, targetClass: null },
            { key: "createdBy", name: "등록자", type: "code", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "updatedBy", name: "수정자", type: "code", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "createdAt", name: "등록일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "updatedAt", name: "수정일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "endOfService", name: "서비스 종료일", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "importDate", name: "도입일자", type: "date", typeName: "LocalDateTime", subClass: null, subValue: null, targetClass: null },
            { key: "importPrice", name: "도입금액", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "mngPrice", name: "유지보수액", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "mngRate", name: "유지보수율", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "etc", name: "부가정보", type: null, typeName: null, subClass: null, subValue: null, targetClass: null },
            { key: "operator", name: "운영 담당자", type: "array", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "handler", name: "자산 사용자", type: "array", typeName: "UserAccount", subClass: null, subValue: null, targetClass: null },
            { key: "assetCustomCodesψ22", name: "IP(하드웨어)(C_146)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ23", name: "IP(NAS)(C_101)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ24", name: "자산유형(C_1)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ25", name: "자산유형비고(C_5)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ26", name: "공통코드(테스트용)(C_34)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ27", name: "기타작업(C_10)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ28", name: "기타(C_9)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ29", name: "IP(HB)(C_102)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ30", name: "IP(백업)(C_91)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomCodesψ31", name: "IP(서비스)(C_90)", type: "code", typeName: "CustomCode", subClass: "customCode", subValue: "value", targetClass: "AssetCustomCode" },
            { key: "assetCustomStringsψ32", name: "상태정보(S_1)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ33", name: "테스트정보(S_2)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ34", name: "정보(S_6)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ35", name: "설치일자(S_15)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ36", name: "폐기일자(S_17)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ37", name: "서비스개시일자(S_16)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ38", name: "도입일자(S_7)", type: "date", typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ39", name: "담당업체(S_27)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetCustomStringsψ40", name: "담당자(S_28)", type: null, typeName: "CustomString", subClass: "code", subValue: "value", targetClass: "AssetCustomString" },
            { key: "assetFieldsψ41", name: "네트워크 장비 필드 (F_41)", type: "code", typeName: "UserAccount", subClass: "field", subValue: "value", targetClass: "AssetField" },
            { key: "assetFieldsψ42", name: "서버그룹(F_11)", type: "code", typeName: "GroupSelect", subClass: "field", subValue: "value", targetClass: "AssetField" },
        ],
        data: [
            { id: "280", assetName: "Cisco Nexus 93600CD-GX", assetCode: null, task: "인프라", location: "판교 오피스", slaGroup: "1등급", department: "인프라", project: "신년 프로젝트", mngPrimary: "프롬소프트", mngSecondary: null, mngTertiary: null, createdBy: "최현복", updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2026-04-27T15:38:25.034798", endOfService: "2025-09-12T00:00", importDate: "2025-06-17T00:00", importPrice: null, mngPrice: null, mngRate: null, etc: "데이터센터 집선L3스위치", operator: "", handler: "이영희,최수진,강준호,장미진,김도훈", "assetCustomCodesψ22": "", "assetCustomCodesψ23": "", "assetCustomCodesψ24": "네트워크장비", "assetCustomCodesψ25": "", "assetCustomCodesψ26": "", "assetCustomCodesψ27": "", "assetCustomCodesψ28": "", "assetCustomCodesψ29": "", "assetCustomCodesψ30": "", "assetCustomCodesψ31": "", "assetFieldsψ41": "", "assetFieldsψ42": "유휴" },
            { id: "216", assetName: "엑셀 롤백 테스트 자산7", assetCode: null, task: null, location: "2층 개발실", slaGroup: "1등급", department: "보안팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-03-11T09:50:07.548993", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "", "assetCustomCodesψ22": "", "assetCustomCodesψ23": "", "assetCustomCodesψ24": "유형B", "assetCustomCodesψ25": "", "assetCustomCodesψ26": "no", "assetCustomCodesψ27": "", "assetCustomCodesψ28": "", "assetCustomCodesψ29": "", "assetCustomCodesψ30": "", "assetCustomCodesψ31": "", "assetCustomStringsψ32": "상태정보 비움", "assetCustomStringsψ33": "테스트정보 커스텀 스트링", "assetCustomStringsψ34": "", "assetCustomStringsψ35": "", "assetCustomStringsψ36": "", "assetCustomStringsψ37": "", "assetCustomStringsψ38": "", "assetCustomStringsψ39": "", "assetCustomStringsψ40": "" },
            { id: "211", assetName: "엑셀 롤백 테스트 자산12", assetCode: null, task: null, location: "서버 랙 R-01", slaGroup: "1등급", department: "총무팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-03-11T09:50:07.548993", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "", "assetCustomCodesψ22": "", "assetCustomCodesψ23": "", "assetCustomCodesψ24": "", "assetCustomCodesψ25": "", "assetCustomCodesψ26": "no", "assetCustomCodesψ27": "", "assetCustomCodesψ28": "", "assetCustomCodesψ29": "", "assetCustomCodesψ30": "", "assetCustomCodesψ31": "", "assetCustomStringsψ32": "상태정보 비움", "assetCustomStringsψ33": "테스트정보 커스텀 스트링", "assetCustomStringsψ34": "", "assetCustomStringsψ35": "", "assetCustomStringsψ36": "", "assetCustomStringsψ37": "", "assetCustomStringsψ38": "", "assetCustomStringsψ39": "", "assetCustomStringsψ40": "" },
            { id: "145", assetName: "사내 네트워크망 44", assetCode: null, task: null, location: "Production VPC", slaGroup: "1등급", department: "부산지사", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.354481", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "140", assetName: "사내 네트워크망 39", assetCode: null, task: null, location: "1층", slaGroup: "1등급", department: "데이터분석팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.354481", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "135", assetName: "사내 네트워크망 34", assetCode: null, task: null, location: "개발팀 구역", slaGroup: "1등급", department: "국내영업팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.354481", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "130", assetName: "사내 네트워크망 29", assetCode: null, task: null, location: "서버 랙 R-02", slaGroup: "1등급", department: "IT운영부", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.355497", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "125", assetName: "사내 네트워크망 24", assetCode: null, task: null, location: "Development VPC", slaGroup: "1등급", department: "인사팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.355497", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "120", assetName: "사내 네트워크망 19", assetCode: null, task: null, location: "로비", slaGroup: "1등급", department: "시장분석팀", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.355497", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "115", assetName: "사내 네트워크망 14", assetCode: null, task: null, location: "회의실 201", slaGroup: "1등급", department: "서울지사", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.355497", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "110", assetName: "사내 네트워크망 9", assetCode: null, task: null, location: "네트워크 장비실", slaGroup: "1등급", department: "영업부", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.355497", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
            { id: "105", assetName: "사내 네트워크망 4", assetCode: null, task: null, location: "ap-northeast-2c (AZ)", slaGroup: "1등급", department: "데브옵스", project: null, mngPrimary: null, mngSecondary: null, mngTertiary: null, createdBy: null, updatedBy: null, createdAt: "2026-01-01T00:00", updatedAt: "2025-02-20T15:21:04.355497", endOfService: null, importDate: null, importPrice: null, mngPrice: null, mngRate: null, etc: null, operator: "", handler: "" },
        ],
        errors: null,
    },
};
